# general configuration
debug: true
base_url: /newLabProy/
enableMarkdown: true            # markdown processor
ajaxPath: /q                    # path added to the url to get ajax templates

# folders
twigs: /twigs                   # main twigs folder
log: /log.log                   # use 'false' to disable logger

# template autoloader
autoloader:
  autoload: /twigs/autoload
  autoload2: /twigs/autoload2

# REQUIRED # import as it generates the routing system and the seo contents
    # the data uses this structure: https://docs.google.com/spreadsheet/ccc?key=0AtJGbTMFIBvQdDJKMzhmMHVZNGRhYmNSc2FyYWZTTlE&usp=sharing
routing:
  url: routes.csv
  format: csv
  indexColumn: name
  exposeJS: false
  exposeTWIG: true
  initialRoute: home

# data imports => use this to use external data files (csv and json) directly into your twig or js
    # url can be a local or external file
dataImports:
  dinamicSections:
    url: https://docs.google.com/spreadsheet/pub?key=0AtJGbTMFIBvQdEFHTExYZmFLXzg1WTFaUWNQd3I2ZFE&single=true&gid=0&output=csv
    format: csv
    indexColumn:
    routing:
      ajax: false
      route: sections
      name: title
      title: intro
      url: title
    exposeJS: true
    exposeTWIG: true
    preprocess: myDataProcessorSample